name: Guilherme Zilli
markdown: kramdown


permalink: /blog/:year/:month/:day/:title
paginate: 5
paginate_path: "/blog/page:num/"
theme: minima

minima:
  social_links:
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/guilhermezilli" }

